Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 35

Style/DotPosition:
  EnforcedStyle: trailing

Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.2