require 'watir-webdriver'

require 'demoqa/billing_data_model'
require 'demoqa/page_base'
require 'demoqa/landing_page'
require 'demoqa/products_list_page'
require 'demoqa/checkout_page'
require 'demoqa/details_page'
require 'demoqa/my_account_page'
require 'demoqa/shopping_cart_page'
